#cloud-config
users:
  - name: ubuntu  # Erstelle den Benutzer "ubuntu"
    sudo: ALL=(ALL) NOPASSWD:ALL  # Volle sudo-Rechte ohne Passwortabfrage
    groups: users, admin  # Weist den Benutzer den Gruppen "users" und "admin" zu
    home: /home/ubuntu  # Definiert das Home-Verzeichnis
    shell: /bin/bash  # Setzt die Standard-Shell auf Bash
    ssh_authorized_keys:  # Hinterlegt autorisierte SSH-Schlüssel
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTdUeU5/u4I1yXbe6NXTT/SYJpeZKSI1QWACwT3A62axs5IhJQie8lfN5MNcc6ghN7tQTVY8zGOloWqWy7noqqVmVpadZUtJzgTfDj2hRSbgCrscPiRpolOgCrjlvG3ANQ5hL4YbBYzzDgEn12HD8nIdjaak/DapUYAPaRdydSOZ3xSwXkXC0iQPrgykG3Kq418jFmnvEq2vnDWrDXW07CyeD4uyDxtAKwOz2rsJjtKuNI2aTpDv1l0fgtFF9FZ+3cgbH1Q6fKkE+bVaf9W84HJ1a5q+IyNLkgeOg1ON7jwRIVX21L8hqslfr4fn46aafnv5C7IIYOnKmtiLNA9DoD  # Beispiel-SSH-Key

# Aktualisiere die Paketliste und installiere notwendige Pakete
package_update: true  # Führt ein apt-get update aus
# Schreibe Dateien in das Webverzeichnis
write_files:
  - path: /var/www/html/index.html  # Begrüßungsseite
    content: |
      <html>
        <head><title>Webserver</title></head>
        <body>
          <h1>Willkommen auf Levis Webserver!</h1>
        </body>
      </html>
  - path: /var/www/html/info.php  # PHP-Info-Seite für Debugging
    content: |
      <?php
        phpinfo();  // Zeigt PHP-Informationen an
      ?>
  - path: /var/www/html/db.php  # PHP-Skript zur Datenbankabfrage
    content: |
      <html>
      <head></head>
      <body>
      Diese Seite macht eine Abfrage auf die Datenbank. <br />
      Das ausgeführte Query ist: <i>select Host, User from mysql.user;</i><br /><br />
      Das Resultat: <br />
      <?php
              // Datenbankverbindung
              $servername = "172.31.64.20";  // IP-Adresse der Datenbank
              $username = "admin";  # Benutzername der Datenbank
              $password = "levi1234";  # Passwort der Datenbank (Klartext: unsicher)
              $dbname = "mysql";  # Datenbankname

              // Verbindung herstellen
              $conn = new mysqli($servername, $username, $password, $dbname);
              if ($conn->connect_error) {  # Fehlerbehandlung bei Verbindungsfehlern
                      die("Connection failed: " . $conn->connect_error);
              }

              $sql = "select Host, User from mysql.user;";  # SQL-Abfrage
              $result = $conn->query($sql);
              while($row = $result->fetch_assoc()){  # Ausgabe der Ergebnisse
                      echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
              }
      ?>
      </body>
      </html>

# Befehle zur Laufzeit
runcmd:
  - sudo apt update
  - sudo apt install apache2 php php-mysqli adminer libapache2-mod-php
  - sudo a2enconf adminer  # Aktiviert die Adminer-Konfiguration in Apache
  - sudo systemctl restart apache2  # Startet Apache neu
  - sudo systemctl enable apache2  # Aktiviert Apache beim Booten
