#cloud-config
users: # Die Benutzer
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # Rechte
    groups: users, admin #Rechte
    home: /home/ubuntu # Home Pfad
    shell: /bin/bash # Shell
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTdUeU5/u4I1yXbe6NXTT/SYJpeZKSI1QWACwT3A62axs5IhJQie8lfN5MNcc6ghN7tQTVY8zGOloWqWy7noqqVmVpadZUtJzgTfDj2hRSbgCrscPiRpolOgCrjlvG3ANQ5hL4YbBYzzDgEn12HD8nIdjaak/DapUYAPaRdydSOZ3xSwXkXC0iQPrgykG3Kq418jFmnvEq2vnDWrDXW07CyeD4uyDxtAKwOz2rsJjtKuNI2aTpDv1l0fgtFF9FZ+3cgbH1Q6fKkE+bVaf9W84HJ1a5q+IyNLkgeOg1ON7jwRIVX21L8hqslfr4fn46aafnv5C7IIYOnKmtiLNA9DoD

ssh_pwauth: false # Passwort Authentifikation
disable_root: false # Kein Root
package_update: true # Packages updaten
runcmd: # wird automatisch gerunnt
 - sudo apt update
 - sudo apt install mariadb-server
 -  sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'levi1234' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb
  - sudo systemctl enable mariadb