#cloud-config
users:
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # Admin-Rechte ohne Passwort
    groups: users, admin # Mitglied in "users" und "admin"
    home: /home/ubuntu # Home-Verzeichnis
    shell: /bin/bash # Standard-Shell
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key # SSH-Schlüssel
ssh_pwauth: false # Passwort-Authentifizierung für SSH deaktiviert
disable_root: false # Root-Benutzer bleibt aktiviert
package_update: true # Paketliste wird aktualisiert
packages:
  - curl # Installiert curl
  - wget # Installiert wget
